### ISSUE TITLE
Error: Cannot find native module 'ExpoClavePasskey', js engine: hermes

### ISSUE THREAD

**Issue by wuchiajung** [getclave/clave-expo-passkey#2]
I added '@getclave/expo-passkey' using yarn with the command yarn add @getclave/expo-passkey. After using the import statement import { Passkey } from '@getclave/expo-passkey';

 I encountered the following error upon building:

Error: Cannot find native module 'ExpoClavePasskey', js engine: hermes.

How can I resolve this issue?

**Comment by hmzdot** [comment]
In order to work with the passkey library, you need to run `pod install` inside the iOS folder as well.

**Comment by wuchiajung** [comment]
I am testing using Android.
I'm running this sample on Android.
Clicking on "createPasskey" does not respond.
May I ask what else I need to pay attention to?

I've tried testing with "npx expo run:android".
I've also tried building the APK and installing it on the phone.
However, it still doesn't work. What else should I pay attention to?
thanks!
